### ISSUE TITLE
Arbitrary user-provided code execution

### ISSUE THREAD

**Issue by glb** [RafalWilinski/deploy-with-serverless#14]
It appears that an attacker could cause your batch job to run arbitrary code in your account by specifying the URL of a github project that they own, or by specifying commands that they want to run in the `BEFORE_CMD`, `PACKAGE_CMD`, or `AFTER_CMD`.

This is a great idea for a service, but it would be safer if you set up a registry of the packages that you want to make available and then allow people to reference packages by ID instead of providing this kind of arbitrary execution power.

**Comment by RafalWilinski** [comment]
Totally agree. @alexcasalboni also pointed out to me this vulnerability. Thanks for both of you! 💯 

I've just commented out all `eval`s and pushed new Docker image without before, override and after functionality. I'll try to come up with safer solution asap
